name: Deploy on Merge to Main

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies if needed (make sure you have a requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Step 4: Run the Python deploy script
      - name: Run deployment script
        env:
          user: ${{ secrets.DB_USER }}
          password: ${{ secrets.DB_PASSWORD }}
          host: ${{ secrets.DB_HOST }}
          port: ${{ secrets.DB_PORT }}
          dbname: ${{ secrets.DB_NAME }}
        run: python deploy_migrations.py
